"use client";

import { FaShieldAlt, FaFingerprint, FaNetworkWired } from "react-icons/fa";

export default function ProofOfValidation() {
  return (
    <section
      id="proof"
      className="w-full min-h-screen bg-gradient-to-b from-gray-950 to-black text-white px-6 pt-24 pb-16 flex flex-col items-center"
    >
      <h2 className="text-3xl md:text-5xl font-bold text-center text-green-400 mb-6">
        Proof of Validation
      </h2>

      <p className="text-gray-300 text-md md:text-lg max-w-3xl text-center mb-12">
        This section demonstrates how World ID integrates with Hyperchain environments by validating zero-knowledge proofs, ensuring the uniqueness of users, and supporting secure authentication flows in both local and testnet chains.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-6xl">
        {/* Proof Validation */}
        <div className="bg-gray-900 rounded-2xl p-6 shadow-lg border border-gray-700 hover:border-green-400 transition">
          <FaShieldAlt className="text-green-400 text-4xl mb-4" />
          <h3 className="text-xl font-semibold mb-2">ZK Proof Handling</h3>
          <p className="text-sm text-gray-400 leading-relaxed">
            Validate World ID zk-SNARKs generated by the client through the Semaphore protocol.
            Smart contracts check the signal hash, nullifier hash, and Merkle root to confirm legitimacy.
          </p>
        </div>

        {/* Identity Uniqueness */}
        <div className="bg-gray-900 rounded-2xl p-6 shadow-lg border border-gray-700 hover:border-green-400 transition">
          <FaFingerprint className="text-green-400 text-4xl mb-4" />
          <h3 className="text-xl font-semibold mb-2">Unique Identity Enforcement</h3>
          <p className="text-sm text-gray-400 leading-relaxed">
            Prevent duplicate submissions by leveraging the nullifier hash, which uniquely represents each user's verification without revealing their identity.
          </p>
        </div>

        {/* Hyperchain Integration */}
        <div className="bg-gray-900 rounded-2xl p-6 shadow-lg border border-gray-700 hover:border-green-400 transition">
          <FaNetworkWired className="text-green-400 text-4xl mb-4" />
          <h3 className="text-xl font-semibold mb-2">Hyperchain Compatibility</h3>
          <p className="text-sm text-gray-400 leading-relaxed">
            Designed for full compatibility with Hyperchains running locally or on testnets. Simulate realistic verification flows and contract calls in an isolated environment.
          </p>
        </div>
      </div>
    </section>
  );
}
